// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolHub.Mvc.Data;

#nullable disable

namespace VolHub.Mvc.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029215031_Lab4Events")]
    partial class Lab4Events
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.21");

            modelBuilder.Entity("VolHub.Mvc.Models.AppUserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("VolHub.Mvc.Models.EventCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventCategories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Прибирання парків, сортування відходів, зелені ініціативи.",
                            Name = "Екологічні акції"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Лекції, майстер-класи та наставництво для громад.",
                            Name = "Освітні заходи"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Допомога людям похилого віку, центрам тимчасового перебування та військовим.",
                            Name = "Соціальна підтримка"
                        });
                });

            modelBuilder.Entity("VolHub.Mvc.Models.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Room")
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name", "City")
                        .IsUnique();

                    b.ToTable("Venues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "вул. Шевченка, 12",
                            City = "Київ",
                            Name = "Центральний парк"
                        },
                        new
                        {
                            Id = 2,
                            Address = "пл. Ринок, 5",
                            City = "Львів",
                            Name = "Освітній простір «Knowledge Hub»",
                            Room = "Зал 2"
                        },
                        new
                        {
                            Id = 3,
                            Address = "пр-т Гагаріна, 101",
                            City = "Дніпро",
                            Name = "Волонтерський штаб «Разом»"
                        });
                });

            modelBuilder.Entity("VolHub.Mvc.Models.VolunteerEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("EventCategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Organizer")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("TEXT");

                    b.Property<int>("VenueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EventCategoryId");

                    b.HasIndex("StartDateUtc");

                    b.HasIndex("VenueId");

                    b.ToTable("VolunteerEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 120,
                            CreatedUtc = new DateTime(2025, 10, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            EndDateUtc = new DateTime(2025, 11, 15, 10, 0, 0, 0, DateTimeKind.Utc),
                            EventCategoryId = 1,
                            Organizer = "VolHub Community",
                            StartDateUtc = new DateTime(2025, 11, 15, 6, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Командне прибирання берега Дніпра з сортуванням зібраного пластику.",
                            Title = "Осіннє прибирання Дніпра",
                            VenueId = 1
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 45,
                            CreatedUtc = new DateTime(2025, 10, 5, 8, 0, 0, 0, DateTimeKind.Utc),
                            EndDateUtc = new DateTime(2025, 12, 2, 16, 0, 0, 0, DateTimeKind.Utc),
                            EventCategoryId = 2,
                            Organizer = "Digital Volunteers UA",
                            StartDateUtc = new DateTime(2025, 12, 2, 13, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Навчання базовим онлайн-сервісам для літніх людей та внутрішньо переміщених осіб.",
                            Title = "Майстер-клас з цифрової грамотності",
                            VenueId = 2
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 80,
                            CreatedUtc = new DateTime(2025, 10, 12, 11, 0, 0, 0, DateTimeKind.Utc),
                            EndDateUtc = new DateTime(2025, 12, 10, 12, 0, 0, 0, DateTimeKind.Utc),
                            EventCategoryId = 3,
                            Organizer = "Разом сильніші",
                            StartDateUtc = new DateTime(2025, 12, 10, 7, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Сортування, пакування та доставка теплого одягу до пункту підтримки.",
                            Title = "Збір теплих речей для центру підтримки",
                            VenueId = 3
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 60,
                            CreatedUtc = new DateTime(2025, 10, 20, 7, 30, 0, 0, DateTimeKind.Utc),
                            EndDateUtc = new DateTime(2026, 1, 20, 21, 0, 0, 0, DateTimeKind.Utc),
                            EventCategoryId = 1,
                            Organizer = "Cycle Impact",
                            StartDateUtc = new DateTime(2026, 1, 20, 17, 0, 0, 0, DateTimeKind.Utc),
                            Summary = "Велосипедний патруль із прибиранням набережної та сортуванням сміття.",
                            Title = "Нічний велозаїзд з прибиранням",
                            VenueId = 1
                        });
                });

            modelBuilder.Entity("VolHub.Mvc.Models.VolunteerEvent", b =>
                {
                    b.HasOne("VolHub.Mvc.Models.EventCategory", "EventCategory")
                        .WithMany("Events")
                        .HasForeignKey("EventCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolHub.Mvc.Models.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventCategory");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VolHub.Mvc.Models.EventCategory", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("VolHub.Mvc.Models.Venue", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
